// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: byte_message.proto

package messages 

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// example:
// t: "MPC.keygen.create.to_server"
// conn_id: "cea0172c-e75e-4ed1-920d-1ee53f6858b9"
// content: 0x0123456789abcdef
// comment: "this is an example"
// # gid: "cea0172c-e75e-4ed1-920d-1ee53f6858b9"
// # mid: "47e5a377-f68f-4da7-8cc0-c55e52533a03"
// # gid, mid 之类的放到 content 里，不一定用到
type ByteMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	T       string `protobuf:"bytes,1,opt,name=t,proto3" json:"t,omitempty"`                         // message type: <category>.<type>.<stage>.<other>
	ConnId  string `protobuf:"bytes,2,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"` // websocket connect id: 由服务器创建
	Content []byte `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`             // message content of bytes
	Comment string `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`             // 其他内容或备用
}

func (x *ByteMessage) Reset() {
	*x = ByteMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_byte_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ByteMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ByteMessage) ProtoMessage() {}

func (x *ByteMessage) ProtoReflect() protoreflect.Message {
	mi := &file_byte_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ByteMessage.ProtoReflect.Descriptor instead.
func (*ByteMessage) Descriptor() ([]byte, []int) {
	return file_byte_message_proto_rawDescGZIP(), []int{0}
}

func (x *ByteMessage) GetT() string {
	if x != nil {
		return x.T
	}
	return ""
}

func (x *ByteMessage) GetConnId() string {
	if x != nil {
		return x.ConnId
	}
	return ""
}

func (x *ByteMessage) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ByteMessage) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

var File_byte_message_proto protoreflect.FileDescriptor

var file_byte_message_proto_rawDesc = []byte{
	0x0a, 0x12, 0x62, 0x79, 0x74, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x69, 0x0a, 0x0c, 0x62, 0x79,
	0x74, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x6e, 0x49,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x0a, 0x5a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_byte_message_proto_rawDescOnce sync.Once
	file_byte_message_proto_rawDescData = file_byte_message_proto_rawDesc
)

func file_byte_message_proto_rawDescGZIP() []byte {
	file_byte_message_proto_rawDescOnce.Do(func() {
		file_byte_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_byte_message_proto_rawDescData)
	})
	return file_byte_message_proto_rawDescData
}

var file_byte_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_byte_message_proto_goTypes = []interface{}{
	(*ByteMessage)(nil), // 0: main.byte_message
}
var file_byte_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_byte_message_proto_init() }
func file_byte_message_proto_init() {
	if File_byte_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_byte_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ByteMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_byte_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_byte_message_proto_goTypes,
		DependencyIndexes: file_byte_message_proto_depIdxs,
		MessageInfos:      file_byte_message_proto_msgTypes,
	}.Build()
	File_byte_message_proto = out.File
	file_byte_message_proto_rawDesc = nil
	file_byte_message_proto_goTypes = nil
	file_byte_message_proto_depIdxs = nil
}
